.TH "ALU" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ALU
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetInput_1\fP (string in_1)"
.br
.ti -1c
.RI "void \fBsetInput_2\fP (string in_2)"
.br
.ti -1c
.RI "void \fBsetOperation\fP (string op)"
.br
.ti -1c
.RI "void \fBperformOperation\fP ()"
.br
.ti -1c
.RI "string \fBgetResult\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void ALU::performOperation ()"
Add : add, addi
.PP
Subtract : sub
.PP
Compare : beq 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
