.TH "Converter" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Converter
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBhextoint\fP (std::string s)"
.br
.ti -1c
.RI "static string \fBinttohex\fP (int x)"
.br
.ti -1c
.RI "static string \fBhexToBinary\fP (string hex)"
.br
.ti -1c
.RI "static string \fBbinaryToHex\fP (string binary)"
.br
.ti -1c
.RI "static std::string \fBhexify\fP (std::string s)"
.br
.ti -1c
.RI "static std::string \fBinttobinarry\fP (int a)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static string Converter::binaryToHex (string binary)\fC [inline]\fP, \fC [static]\fP"
Converts a given binary value to hex 
.PP
\fBParameters:\fP
.RS 4
\fIbinary\fP binary value to be changed to a hex value 
.RE
.PP
\fBReturns:\fP
.RS 4
hex hexadecimal conversion of the provided binary value 
.RE
.PP
string that will hold final hex string to return
.PP
string to extend input string so length is divisible by 4
.PP
string that will hold 4 bit chunks of input string
.PP
Extend inputted string to be of a length divisible by 4
.PP
append extender to front of binary string
.PP
Loop through 4 bit chunks of binary string, appending to hex string 
.SS "static std::string Converter::hexify (std::string s)\fC [inline]\fP, \fC [static]\fP"
Checking if it already has '0x' in the begging of the string 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP string to be converted to it's hex equivalent 
.RE
.PP
\fBReturns:\fP
.RS 4
mystring the hexadeciaml conversion of the provided string 
.RE
.PP

.SS "static string Converter::hexToBinary (string hex)\fC [inline]\fP, \fC [static]\fP"
Converts a given hex value to binary 
.PP
\fBParameters:\fP
.RS 4
\fIhex\fP hex value to be changed to a binary value 
.RE
.PP
\fBReturns:\fP
.RS 4
bin binary conversion of the provided hex value 
.RE
.PP
Get the next char in the hex
.PP
Convert the next char in the hex to the appropriate 4-bit binary representation 
.SS "static int Converter::hextoint (std::string s)\fC [inline]\fP, \fC [static]\fP"
Converts a given hex value to an int 
.PP
\fBParameters:\fP
.RS 4
\fIs\fP hex input to be changed to an int value 
.RE
.PP
\fBReturns:\fP
.RS 4
integer conversion of the provided hex value 
.RE
.PP

.SS "static std::string Converter::inttobinarry (int a)\fC [inline]\fP, \fC [static]\fP"
Converts given int value into binary 
.PP
\fBParameters:\fP
.RS 4
\fIa\fP integer value to be converted to it's binary equivalent 
.RE
.PP
\fBReturns:\fP
.RS 4
bin thebinary conversion of the provided integer 
.RE
.PP

.SS "static string Converter::inttohex (int x)\fC [inline]\fP, \fC [static]\fP"
Converts a given int value to hex 
.PP
\fBParameters:\fP
.RS 4
\fIx\fP integer value to be changed to a hex value 
.RE
.PP
\fBReturns:\fP
.RS 4
s hexadecimal conversion of the provided integer value 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
