.TH "InstructionMemory" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
InstructionMemory
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInstructionMemory\fP ()"
.br
.RI "Default constructor\&. "
.ti -1c
.RI "\fBInstructionMemory\fP (std::string filename)"
.br
.ti -1c
.RI "\fBInstruction\fP \fBgetInstruction\fP (std::string address)"
.br
.ti -1c
.RI "bool \fBisValidInstruction\fP (std::string theAddress)"
.br
.RI "Checks to make sure that a valid instruction is given\&. "
.ti -1c
.RI "void \fBprintContents\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBInstruction\fP InstructionMemory::getInstruction (std::string theAddress)"
Given an address, will get the instruction associated with the specified address 
.PP
\fBParameters:\fP
.RS 4
\fItheAddress\fP Address given to accessand get the associated \fBInstruction\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
\fBInstruction\fP associated with given address 
.RE
.PP

.SS "void InstructionMemory::printContents ()"
Initializes iterator and iterates through myInstructionMapping, gathering the contents at each \fBInstruction\fP address and printing them out 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
