.TH "Multiplexor" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Multiplexor
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "std::string \fBsetFirstInput\fP (std::string firstInput)"
.br
.RI "Set's input at point that coincides with 0 on the picture\&. "
.ti -1c
.RI "std::string \fBsetSecondInput\fP (std::string secondInput)"
.br
.RI "Sets input at 1 that coincides with 1 on the picture\&. "
.ti -1c
.RI "std::string \fBmux\fP ()"
.br
.RI "calls mux and returns the result chosed "
.ti -1c
.RI "void \fBsetFlow\fP (int \fBflow\fP)"
.br
.ti -1c
.RI "int \fBgetFlow\fP ()"
.br
.RI "Returns signal for testing\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBfirstInput\fP"
.br
.ti -1c
.RI "std::string \fBsecondInput\fP"
.br
.ti -1c
.RI "int \fBflow\fP"
.br
.RI "0 or 1, based on value in the picture of the processor\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Multiplexor::setFlow (int flow)"
will be used by the Control Unit, which sends true or false based on whether or not the mux is needed\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
