.TH "Parser" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Parser
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (string filename)"
.br
.ti -1c
.RI "bool \fBisFormatCorrect\fP ()"
.br
.ti -1c
.RI "\fBInstruction\fP \fBgetNextInstruction\fP ()"
.br
.RI "Iterator that returns the next \fBInstruction\fP in the list of Instructions\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBcvtInt2Bin\fP (int number, size_t length)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Parser::Parser (string filename)"
Specify a text file containing MIPS assembly instructions\&. Function checks syntactic correctness of file and creates a list of Instructions\&. No opcode but operands
.PP
invalid opcode specified 
.SH "Member Function Documentation"
.PP 
.SS "bool Parser::isFormatCorrect ()\fC [inline]\fP"
Returns true if the file specified was syntactically correct\&. Otherwise, returns false\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
