.TH "ProgramCounter" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ProgramCounter \- This h creates the guidlines for the program counter\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ProgramCounter\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBProgramCounter\fP ()"
.br
.RI "This creates the program counter object\&. "
.ti -1c
.RI "\fBProgramCounter\fP (std::string address)"
.br
.ti -1c
.RI "std::string \fBgetCurrentAddress\fP ()"
.br
.ti -1c
.RI "std::string \fBmoveAddressTo\fP (std::string newAddress)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This h creates the guidlines for the program counter\&. 

forward declarations needed can go below 
.SH "Member Function Documentation"
.PP 
.SS "std::string ProgramCounter::getCurrentAddress ()"
getCurrentAddress will return the current address of the program counter as a string 
.SS "std::string ProgramCounter::moveAddressTo (std::string newAddress)"
moveAddressTo will move the address in the PC to a given point, will will be used for j type and branch instructions\&. This method will be called by control??
.PP
moveAddressTo will move the address in the PC to a given point, will will be used for j type and branch instructions 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
