.TH "ShiftLeftTwo" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ShiftLeftTwo \- Used to shift the offset field to the left by two, making it a word offset\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ShiftLeftTwo\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBShift\fP (std::string offsetField)"
.br
.RI "shifts the offset field to the left by two bits, making it a word offset "
.in -1c
.SH "Detailed Description"
.PP 
Used to shift the offset field to the left by two, making it a word offset\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
