.TH "SignExtend" 3 "Thu Apr 26 2018" "CS 301 FinalProj" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SignExtend
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBExtend\fP (std::bitset< 16 > sign_extend_val)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for CS 301 FinalProj from the source code\&.
